### PR TITLE
8.1.5 workarounds

### PR DESCRIPTION
**Pull request by Tuller**
ItemSlots are their own frame class now.

### CODE REVIEW

**Comment by pmgower** [comment]
I would like to get these fixes integrated into my local version of Bagnon until @Jaliborc has time to review this PR.  @Tuller how can i do that on my local machine?  I see the **external/Wildpants** folder but there aren't any files in there because it's referencing them externally.  Is there an easy trick to setting it to point to my local version and use this PR version?

**Comment by Jaliborc** [comment]
I see... I wonder what in the world made them create a new frame type.

**Comment by pmgower** [comment]
@Tuller and @Jaliborc where's the best source for LUA WoW addon programming?  I'm a programmer but not done much addon programming in WoW.  In my day job I use [http://stackoverflow.com](http://stackoverflow.com) is there an equivalent in WoW LUA Addon programming? 😄

**Comment by LudiusMaximus** [comment]
> @Tuller and @Jaliborc where's the best source for LUA WoW addon programming? I'm a programmer but not done much addon programming in WoW. In my day job I use http://stackoverflow.com is there an equivalent in WoW LUA Addon programming? 😄

In my oppinion definitely: https://www.wowinterface.com/forums/forumdisplay.php?f=16
I just started programming WoW Lua a year ago. The beginning is rather rough because I only found rudimentary/outdated tutorials which often focus on something you might not really need. For me the best entry was to reverse-engineer/fix other addons I liked. The people in the wowinterface forum are extremely helpful and knowledgable. Otherwise there is this book, which is probalby good: https://books.google.de/books?id=tOSDV71ND_0C&printsec=frontcover&hl=de#v=onepage&q&f=false

**Comment by LudiusMaximus** [comment]
> I would like to get these fixes integrated into my local version of Bagnon until @Jaliborc has time to review this PR. @Tuller how can i do that on my local machine? I see the **external/Wildpants** folder but there aren't any files in there because it's referencing them externally. Is there an easy trick to setting it to point to my local version and use this PR version?

You can do a **recursive** git checkout of Bagnon that will automatically checkout all the referenced submodules including Wildpants. Then you have to switch the branch of Wildpants to this PR.

**Pull request merged**
