### PR TITLE
ItemSlot:UpdateLocked() fix

### PR DESCRIPTION
**Pull request by LudiusMaximus**
I noticed that items do not get greyed out in the bag, when I put them into a mail. The reason seems to be that self.info.locked is never set properly. The addition of this code line seems to fix it...

### CODE REVIEW

**Comment by Jaliborc** [comment]
Not a valid solution. _.info_ is a read only variable

**Comment by LudiusMaximus** [comment]
Interesting. Do you mean self.info _should_ not be written or it _cannot_ be written? Beacuse in another Bagnon plugin I am working on, I can read self.info.locked and it seems to be holding the value I am setting in ItemSlot:UpdateLocked().

**Comment by Jaliborc** [comment]
Should not

**Comment by LudiusMaximus** [comment]
All right. Fair enough. I understand that you want to fix it properly or not at all. :-)
Just for me this dirty fix allows me to have greyed out itmes in the bag while packing them into mails. That's all I wanted for the moment and I thought maybe you would like to use this as an intermediate solution for other users as well... But if I am the first one who has been bothered by the items not being greyed out then you may very well ignore it. Thanks anyway for Bagnon!!

**Comment by LudiusMaximus** [comment]
Could you point me into the direction of how to fix this properly? I really like the locked items being greyed out, but I would also like to go back to getting Bagnon via Twitch app instead of unsing my github fork all the time...

Otherwise, would you mind a makeshift "plugin" consisting of:

if IsAddOnLoaded("Bagnon") then
` `hooksecurefunc(Bagnon.ItemSlot, "UpdateLocked",
` ` ` `function(self)
` ` ` ` ` `_, _, self.info.locked = GetContainerItemInfo(self:GetBag(), self:GetID())
` ` ` ` ` `self:SetLocked(self.info.locked)
` ` ` `end
` `)
end

**Pull request closed without merging**
