### PR TITLE
Fixed for Classic 1.13.2

### PR DESCRIPTION
**Pull request by xionglingfeng**
The addon is now working with Classic.

SortBag is not fixed
Some features are disabled. However, it may be possible to implement those (marked with TODO) with old-school methods (e.g. database libraries)...

### CODE REVIEW

**Comment by Jaliborc** [comment]
Thank you, this is a great start.

**Comment by xionglingfeng** [comment]
I'm now trying go back into history to see how features like `IsQuestItem()` implemented in the past... I remember there are a bunch of libraries doing this kind of database lookup thing...
However, this PR at least make Bagnon work in Classic server...

**Comment by Jaliborc** [comment]
Gonna start updating Bagnon now

**Review by Jaliborc — APPROVED** [review]
Good start, will run with this and maybe clean up some things.

**Pull request merged**
